name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create profile directory
        run: mkdir -p profile

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=AdarshSingh4455&show_icons=true&theme=tokyonight&hide_border=true&bg_color=0f172a&title_color=00c3ff&icon_color=00c3ff&text_color=ffffff
          path: profile/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=AdarshSingh4455&layout=compact&theme=tokyonight&hide_border=true&bg_color=0f172a&title_color=00c3ff&text_color=ffffff
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=AdarshSingh4455&theme=tokyonight&hide_border=true&background=0f172a&ring=00c3ff&fire=00c3ff&currStreakLabel=00c3ff&sideLabels=00c3ff&dates=ffffff
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git diff --cached --quiet || git commit -m "Update GitHub stats"

          git push
